version: "2.35.0"
services:
  web-interface:
    build: .
    ports:
      - "80:80"
    networks:
      high-table:
        ipv4_address: 10.0.0.3
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: cli_pat
      MARIADB_USER: user
      MARIADB_PASSWORD: password

    ports:
      - "3306:3306"
    networks:
      high-table:
        ipv4_address: 10.0.0.4

networks:
  high-table:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
