version: "2.35.0"
services:
  web-interface:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: cli_pat
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
